FROM python:3.10.11-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    gcc \
    libffi-dev \
    libssl-dev \
    ffmpeg \
    libopus-dev \
    supervisor \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./etc/supervisord.conf /etc/supervisord.conf

WORKDIR /app

COPY . /app

ENTRYPOINT [ "supervisord" ]

CMD [ "-c", "/etc/supervisord.conf" ]