name: Deploy to Heroku Beta

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Heroku Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.heroku.com
        username: _
        password: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push Docker image
      env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        docker build -t registry.heroku.com/${{ secrets.HEROKU_BETA_APP_NAME }}/worker --build-arg DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -f Dockerfile .
        docker push registry.heroku.com/${{ secrets.HEROKU_BETA_APP_NAME }}/worker


    - name: Release Docker image as worker
      run: |
        heroku container:release worker --app ${{ secrets.HEROKU_BETA_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_BETA_API_KEY }}

