name: Deploy to Heroku Beta

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Heroku Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.heroku.com
        username: _
        password: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push Docker image
      run: |
        docker build -t registry.heroku.com/${{ secrets.HEROKU_BETA_APP_NAME }}/worker -f Dockerfile .
        docker push registry.heroku.com/${{ secrets.HEROKU_BETA_APP_NAME }}/worker


    - name: Heroku Deploy
      uses: akhileshns/heroku-deploy@v3.12.12  # La versión más reciente al momento de escribir
      with:
        heroku_api_key: ${{ secrets.HEROKU_BETA_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_BETA_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        usedocker: true

